### ISSUE TITLE
Refactor: InterviewBoard 관련 리팩토링

### ISSUE THREAD

**Issue by cloudisme99** [HynssFashionLog/Fashion-Log#106]
## TODO
  - [x] InterviewBoard 엔티티에 `@Setter` 제거와 더티체킹 로직 포함
  - [x] InterviewBoard Dto 빌더 패텬으로 리팩토링
  - [x] InterviewBoard를 불러올 때 status가 `true` 값들만 받아오도록 리팩토링
