### ISSUE TITLE
Fix: InterviewBoard 게시글, 댓글 관련 오류 수정

### ISSUE THREAD

**Issue by cloudisme99** [HynssFashionLog/Fashion-Log#118]
## TODO
  - [ ] 게시글 새 글 등록이 안되는 문제 fix
  - [ ] 댓글 입력창에 내용이 적혀있는 문제 fix
  - [ ] status가 true인 댓글만 보여지도록 fix
