### ISSUE TITLE
Refactor: 권한 검사 시스템 개선 및 게시판 서비스 리팩토링

### ISSUE THREAD

**Issue by LLSNsssz** [HynssFashionLog/Fashion-Log#133]
## TODO
1. 권한 검사 관련 핵심 컴포넌트
  - [x] AuthCheck 어노테이션 수정
  - [x] AuthorizationAspect 개선
  - [x] AuthorType 열거형 클래스 구현

2. DTO 수정
  - [x] DailyLookCommentDto 수정
  - [x] DailyLookDto 수정
  - [x] FreeBoardCommentDto 수정
  - [x] FreeBoardDto 수정
  - [x] InterviewBoardCommentDto 수정
  - [x] InterviewBoardDto 수정
  - [x] LookbookCommentDto 수정
  - [x] LookbookDto 수정
  - [x] NoticeCommentDto 수정
  - [x] NoticeDto 수정

3. 서비스 계층 수정
 - [x] BoardService 인터페이스 구현 (게시글, 댓글 작성자 검증용)
 - [x] CurrentUserProvider 구현
 - [x] DailyLookService
 - [x] FreeBoardService
 - [x] InterviewBoardService
 - [x] LookbookService
 - [x] NoticeService

4. 보안 및 유틸리티
  - [x] SecurityUtil 클래스 구현

5. 엔티티 수정
  - [x] PersistentLogins 엔티티 구현
  - [x] BaseEntity와 CommentBaseEntity 수정
  - [x] CommentBaseEntity 수정

6. 주석 추가 및 업데이트
  - [ ] 주석 추가

## 설명
권한 검사 관련 핵심 컴포넌트: 이 부분은 권한 검사의 기본 구조를 설정합니다. 다른 모든 변경사항의 기초가 되므로 먼저 완료해야 합니다.
DTO 수정: 변경된 권한 검사 로직에 맞춰 DTO를 업데이트합니다.
서비스 계층 수정: 새로운 BoardService 인터페이스를 구현하고, 각 서비스 클래스에 새로운 권한 검사 로직을 적용합니다.
보안 및 유틸리티: SecurityUtil 클래스를 구현하여 현재 사용자 정보를 쉽게 가져올 수 있도록 합니다.
엔티티 수정: 데이터 모델을 업데이트하여 새로운 요구사항을 반영합니다.
문서화: 모든 변경사항에 대해 적절한 주석을 추가하여 코드의 가독성과 유지보수성을 향상시킵니다.
