### ISSUE TITLE
Enhancement: 전반적인 예외 처리

### ISSUE THREAD

**Issue by JEESW** [HynssFashionLog/Fashion-Log#171]
## TODO
  - [x] 댓글 not null 예외 처리
  - [x] 글자 수 예외 처리 (Validation 처리)
  - [x] notice 카테고리 not null
  - [x] 제목의 글자 수가 많을 때 화면 깨짐 처리

## 설명
- 비어있는 댓글이 안 들어가게 컨트롤러 및 서비스 로직에서도 예외 처리 필요함.
- 글자 수가 VARCHAR에 넘어가지 않게 예외 처리를 해야 함.
- 카테고리를 설정하지 않는 경우는 없어야 함.
- 제목의 길이가 길어 질 수 있으므로 긴 제목은 요약하는 방식이 필요함.
![image](https://github.com/user-attachments/assets/86507536-cf69-4ac3-a2e8-651894b446eb)
