### ISSUE TITLE
Refactor: 게시판 UI 개선 및 텍스트 포맷팅

### ISSUE THREAD

**Issue by LLSNsssz** [HynssFashionLog/Fashion-Log#174]
## TODO
  - [x]  긴 제목 자동 개행 처리로 레이아웃 개선
  - [x]  작성일 표시 형식 변경으로 가독성 향상
  - [x]  게시글 본문과 댓글에 자동 개행 적용하여 가독성 개선
