### ISSUE TITLE
Design: CSS 초안 작성

### ISSUE THREAD

**Issue by LLSNsssz** [HynssFashionLog/Fashion-Log#80]
## TODO
   - [x] detail.css 초안 작성
   - [x] list.css 초안 작성
   - [x] edit-form.css 초안 작성
   - [x] styles.css 초안 작성

## 설명
1. `detail.css`: 게시글의 상세 보기를 위한 스타일 정의
2. `list.css`: 기시글 목록을 위한 스타일 정의
3. `edit-form.css`: 글 작성, 글 수정 폼을 위한 스타일 정의
4. `styles.css`: 전체 페이지에 적용되는 공통 스타일 정의
